/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.38.1
  Forc version: 0.35.5
  Fuel-Core version: 0.17.3
*/

import { Interface, Contract } from 'fuels';
import type { Provider, Account, AbstractAddress } from 'fuels';
import type { NFTAbi, NFTAbiInterface } from '../NFTAbi';

const _abi = {
  types: [
    {
      typeId: 0,
      type: '()',
      components: [],
      typeParameters: null,
    },
    {
      typeId: 1,
      type: 'b256',
      components: null,
      typeParameters: null,
    },
    {
      typeId: 2,
      type: 'bool',
      components: null,
      typeParameters: null,
    },
    {
      typeId: 3,
      type: 'enum AccessError',
      components: [
        {
          name: 'SenderCannotSetAccessControl',
          type: 0,
          typeArguments: null,
        },
        {
          name: 'SenderNotAdmin',
          type: 0,
          typeArguments: null,
        },
        {
          name: 'SenderNotOwner',
          type: 0,
          typeArguments: null,
        },
        {
          name: 'SenderNotOwnerOrApproved',
          type: 0,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 4,
      type: 'enum Identity',
      components: [
        {
          name: 'Address',
          type: 12,
          typeArguments: null,
        },
        {
          name: 'ContractId',
          type: 16,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 5,
      type: 'enum InitError',
      components: [
        {
          name: 'AdminIsNone',
          type: 0,
          typeArguments: null,
        },
        {
          name: 'CannotReinitialize',
          type: 0,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 6,
      type: 'enum InputError',
      components: [
        {
          name: 'AdminDoesNotExist',
          type: 0,
          typeArguments: null,
        },
        {
          name: 'ApprovedDoesNotExist',
          type: 0,
          typeArguments: null,
        },
        {
          name: 'NotEnoughTokensToMint',
          type: 0,
          typeArguments: null,
        },
        {
          name: 'OwnerDoesNotExist',
          type: 0,
          typeArguments: null,
        },
        {
          name: 'TokenDoesNotExist',
          type: 0,
          typeArguments: null,
        },
        {
          name: 'TokenSupplyCannotBeZero',
          type: 0,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 7,
      type: 'enum Option',
      components: [
        {
          name: 'None',
          type: 0,
          typeArguments: null,
        },
        {
          name: 'Some',
          type: 8,
          typeArguments: null,
        },
      ],
      typeParameters: [8],
    },
    {
      typeId: 8,
      type: 'generic T',
      components: null,
      typeParameters: null,
    },
    {
      typeId: 9,
      type: 'raw untyped ptr',
      components: null,
      typeParameters: null,
    },
    {
      typeId: 10,
      type: 'str[10]',
      components: null,
      typeParameters: null,
    },
    {
      typeId: 11,
      type: 'str[81]',
      components: null,
      typeParameters: null,
    },
    {
      typeId: 12,
      type: 'struct Address',
      components: [
        {
          name: 'value',
          type: 1,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 13,
      type: 'struct AdminEvent',
      components: [
        {
          name: 'admin',
          type: 7,
          typeArguments: [
            {
              name: '',
              type: 4,
              typeArguments: null,
            },
          ],
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 14,
      type: 'struct ApprovalEvent',
      components: [
        {
          name: 'approved',
          type: 4,
          typeArguments: null,
        },
        {
          name: 'owner',
          type: 4,
          typeArguments: null,
        },
        {
          name: 'token_id',
          type: 23,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 15,
      type: 'struct BurnEvent',
      components: [
        {
          name: 'owner',
          type: 4,
          typeArguments: null,
        },
        {
          name: 'token_id',
          type: 23,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 16,
      type: 'struct ContractId',
      components: [
        {
          name: 'value',
          type: 1,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 17,
      type: 'struct MintEvent',
      components: [
        {
          name: 'owner',
          type: 4,
          typeArguments: null,
        },
        {
          name: 'token_id',
          type: 23,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 18,
      type: 'struct OperatorEvent',
      components: [
        {
          name: 'approve',
          type: 2,
          typeArguments: null,
        },
        {
          name: 'operator',
          type: 4,
          typeArguments: null,
        },
        {
          name: 'owner',
          type: 4,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 19,
      type: 'struct RawVec',
      components: [
        {
          name: 'ptr',
          type: 9,
          typeArguments: null,
        },
        {
          name: 'cap',
          type: 23,
          typeArguments: null,
        },
      ],
      typeParameters: [8],
    },
    {
      typeId: 20,
      type: 'struct TokenMetaData',
      components: [
        {
          name: 'token_uri',
          type: 11,
          typeArguments: null,
        },
        {
          name: 'name',
          type: 10,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 21,
      type: 'struct TransferEvent',
      components: [
        {
          name: 'from',
          type: 4,
          typeArguments: null,
        },
        {
          name: 'sender',
          type: 4,
          typeArguments: null,
        },
        {
          name: 'to',
          type: 4,
          typeArguments: null,
        },
        {
          name: 'token_id',
          type: 23,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 22,
      type: 'struct Vec',
      components: [
        {
          name: 'buf',
          type: 19,
          typeArguments: [
            {
              name: '',
              type: 8,
              typeArguments: null,
            },
          ],
        },
        {
          name: 'len',
          type: 23,
          typeArguments: null,
        },
      ],
      typeParameters: [8],
    },
    {
      typeId: 23,
      type: 'u64',
      components: null,
      typeParameters: null,
    },
  ],
  functions: [
    {
      inputs: [],
      name: 'admin',
      output: {
        name: '',
        type: 7,
        typeArguments: [
          {
            name: '',
            type: 4,
            typeArguments: null,
          },
        ],
      },
      attributes: [
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      inputs: [
        {
          name: 'approved',
          type: 4,
          typeArguments: null,
        },
        {
          name: 'token_id',
          type: 23,
          typeArguments: null,
        },
      ],
      name: 'approve',
      output: {
        name: '',
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
    {
      inputs: [
        {
          name: 'token_id',
          type: 23,
          typeArguments: null,
        },
      ],
      name: 'approved',
      output: {
        name: '',
        type: 7,
        typeArguments: [
          {
            name: '',
            type: 4,
            typeArguments: null,
          },
        ],
      },
      attributes: [
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      inputs: [
        {
          name: 'owner',
          type: 4,
          typeArguments: null,
        },
      ],
      name: 'balance_of',
      output: {
        name: '',
        type: 7,
        typeArguments: [
          {
            name: '',
            type: 23,
            typeArguments: null,
          },
        ],
      },
      attributes: [
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      inputs: [
        {
          name: 'to',
          type: 4,
          typeArguments: null,
        },
        {
          name: 'meta_data',
          type: 22,
          typeArguments: [
            {
              name: '',
              type: 20,
              typeArguments: null,
            },
          ],
        },
      ],
      name: 'batch_mint',
      output: {
        name: '',
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
    {
      inputs: [
        {
          name: 'from',
          type: 4,
          typeArguments: null,
        },
        {
          name: 'to',
          type: 4,
          typeArguments: null,
        },
        {
          name: 'token_ids',
          type: 22,
          typeArguments: [
            {
              name: '',
              type: 23,
              typeArguments: null,
            },
          ],
        },
      ],
      name: 'batch_trasnfer',
      output: {
        name: '',
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
    {
      inputs: [
        {
          name: 'token_id',
          type: 23,
          typeArguments: null,
        },
      ],
      name: 'burn',
      output: {
        name: '',
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
    {
      inputs: [
        {
          name: 'max_supply',
          type: 23,
          typeArguments: null,
        },
      ],
      name: 'change_max_supply',
      output: {
        name: '',
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
    {
      inputs: [
        {
          name: 'access_control',
          type: 2,
          typeArguments: null,
        },
        {
          name: 'admin',
          type: 4,
          typeArguments: null,
        },
        {
          name: 'max_supply',
          type: 23,
          typeArguments: null,
        },
      ],
      name: 'constructor',
      output: {
        name: '',
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
    {
      inputs: [
        {
          name: 'operator',
          type: 4,
          typeArguments: null,
        },
        {
          name: 'owner',
          type: 4,
          typeArguments: null,
        },
      ],
      name: 'is_approved_for_all',
      output: {
        name: '',
        type: 7,
        typeArguments: [
          {
            name: '',
            type: 2,
            typeArguments: null,
          },
        ],
      },
      attributes: [
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      inputs: [],
      name: 'max_supply',
      output: {
        name: '',
        type: 23,
        typeArguments: null,
      },
      attributes: [
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      inputs: [
        {
          name: 'to',
          type: 4,
          typeArguments: null,
        },
        {
          name: 'meta_data',
          type: 20,
          typeArguments: null,
        },
      ],
      name: 'mint',
      output: {
        name: '',
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
    {
      inputs: [
        {
          name: 'token_id',
          type: 23,
          typeArguments: null,
        },
      ],
      name: 'owner_of',
      output: {
        name: '',
        type: 7,
        typeArguments: [
          {
            name: '',
            type: 4,
            typeArguments: null,
          },
        ],
      },
      attributes: [
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      inputs: [
        {
          name: 'admin',
          type: 4,
          typeArguments: null,
        },
      ],
      name: 'set_admin',
      output: {
        name: '',
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
    {
      inputs: [
        {
          name: 'approve',
          type: 2,
          typeArguments: null,
        },
        {
          name: 'operator',
          type: 4,
          typeArguments: null,
        },
      ],
      name: 'set_approval_for_all',
      output: {
        name: '',
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: 'storage',
          arguments: ['write'],
        },
      ],
    },
    {
      inputs: [
        {
          name: 'token_id',
          type: 23,
          typeArguments: null,
        },
      ],
      name: 'token_metadata',
      output: {
        name: '',
        type: 7,
        typeArguments: [
          {
            name: '',
            type: 20,
            typeArguments: null,
          },
        ],
      },
      attributes: [
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      inputs: [],
      name: 'total_supply',
      output: {
        name: '',
        type: 23,
        typeArguments: null,
      },
      attributes: [
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      inputs: [
        {
          name: 'to',
          type: 4,
          typeArguments: null,
        },
        {
          name: 'token_id',
          type: 23,
          typeArguments: null,
        },
      ],
      name: 'transfer',
      output: {
        name: '',
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
    {
      inputs: [
        {
          name: 'from',
          type: 4,
          typeArguments: null,
        },
        {
          name: 'to',
          type: 4,
          typeArguments: null,
        },
        {
          name: 'token_id',
          type: 23,
          typeArguments: null,
        },
      ],
      name: 'transfer_from',
      output: {
        name: '',
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
  ],
  loggedTypes: [
    {
      logId: 0,
      loggedType: {
        name: '',
        type: 6,
        typeArguments: [],
      },
    },
    {
      logId: 1,
      loggedType: {
        name: '',
        type: 3,
        typeArguments: [],
      },
    },
    {
      logId: 2,
      loggedType: {
        name: '',
        type: 14,
        typeArguments: [],
      },
    },
    {
      logId: 3,
      loggedType: {
        name: '',
        type: 17,
        typeArguments: [],
      },
    },
    {
      logId: 4,
      loggedType: {
        name: '',
        type: 6,
        typeArguments: [],
      },
    },
    {
      logId: 5,
      loggedType: {
        name: '',
        type: 3,
        typeArguments: [],
      },
    },
    {
      logId: 6,
      loggedType: {
        name: '',
        type: 21,
        typeArguments: [],
      },
    },
    {
      logId: 7,
      loggedType: {
        name: '',
        type: 6,
        typeArguments: [],
      },
    },
    {
      logId: 8,
      loggedType: {
        name: '',
        type: 3,
        typeArguments: [],
      },
    },
    {
      logId: 9,
      loggedType: {
        name: '',
        type: 15,
        typeArguments: [],
      },
    },
    {
      logId: 10,
      loggedType: {
        name: '',
        type: 6,
        typeArguments: [],
      },
    },
    {
      logId: 11,
      loggedType: {
        name: '',
        type: 3,
        typeArguments: [],
      },
    },
    {
      logId: 12,
      loggedType: {
        name: '',
        type: 5,
        typeArguments: [],
      },
    },
    {
      logId: 13,
      loggedType: {
        name: '',
        type: 6,
        typeArguments: [],
      },
    },
    {
      logId: 14,
      loggedType: {
        name: '',
        type: 5,
        typeArguments: [],
      },
    },
    {
      logId: 15,
      loggedType: {
        name: '',
        type: 6,
        typeArguments: [],
      },
    },
    {
      logId: 16,
      loggedType: {
        name: '',
        type: 17,
        typeArguments: [],
      },
    },
    {
      logId: 17,
      loggedType: {
        name: '',
        type: 3,
        typeArguments: [],
      },
    },
    {
      logId: 18,
      loggedType: {
        name: '',
        type: 13,
        typeArguments: [],
      },
    },
    {
      logId: 19,
      loggedType: {
        name: '',
        type: 18,
        typeArguments: [],
      },
    },
    {
      logId: 20,
      loggedType: {
        name: '',
        type: 6,
        typeArguments: [],
      },
    },
    {
      logId: 21,
      loggedType: {
        name: '',
        type: 3,
        typeArguments: [],
      },
    },
    {
      logId: 22,
      loggedType: {
        name: '',
        type: 21,
        typeArguments: [],
      },
    },
    {
      logId: 23,
      loggedType: {
        name: '',
        type: 6,
        typeArguments: [],
      },
    },
    {
      logId: 24,
      loggedType: {
        name: '',
        type: 3,
        typeArguments: [],
      },
    },
    {
      logId: 25,
      loggedType: {
        name: '',
        type: 21,
        typeArguments: [],
      },
    },
  ],
  messagesTypes: [],
  configurables: [],
};

export class NFTAbi__factory {
  static readonly abi = _abi;
  static createInterface(): NFTAbiInterface {
    return new Interface(_abi) as unknown as NFTAbiInterface;
  }
  static connect(
    id: string | AbstractAddress,
    accountOrProvider: Account | Provider
  ): NFTAbi {
    return new Contract(id, _abi, accountOrProvider) as unknown as NFTAbi;
  }
}
