name: 'Forc Setup'

inputs:
  forc-components:
    default: 'forc@0.67.0, fuel-core@0.41.9'

runs:
  using: 'composite'
  steps:
    - name: Install Fuel toolchain
      uses: FuelLabs/action-fuel-toolchain@v0.6.0
      with:
        name: fuel-bridge
        components: ${{ inputs.forc-components }}
