name: 🐛 Bug Report
description: Something is wrong with Fuel Wallet.
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping to improve our Wallet!

        ## The best bug report is a failing test!

        The fastest way to get a bug fixed is to add a failing test and send a pull request. **It's usually easy to do with our bug report test template**.

        1. Click the "Fork" button
        2. Open our contributions guideline!
        3. Follow the instructions!

        ## I'd rather just report the bug

        That's fine too! Go ahead and fill out this form.

  - type: input
    attributes:
      label: What version of Wallet are you using?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
