name: 🐛 Bug Report
description: Something is wrong with Fuel Wallet.
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping to improve our Wallet!

        ## The best bug report is a failing test!

        The fastest way to get a bug fixed is to add a failing test and send a pull request. **It's usually easy to do with our bug report test template**.

        1. Click the "Fork" button
        2. Open our contributions guideline!
        3. Follow the instructions!

        ## I'd rather just report the bug

        That's fine too! Go ahead and fill out this form.

  - type: input
    attributes:
      label: What version of Wallet are you using?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is happening?
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: steps to reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: How it should behave?
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What os are you seeing the problem on?
      description: Android, iOS, Windows, Mac
      options:
        - Android Mobile
        - iOS Mobile
        - Windows Desktop
        - Mac/Apple Desktop
  - type: dropdown
    attributes:
      label: What browser?
      options:
        - Brave
        - Chrome
        - Firefox
        - Safari
        - Other
  - type: input
    attributes:
      label: What is your browser version?
