version: '3'

services:
  fuel-core:
    platform: linux/amd64
    container_name: '${PROJECT:-fuel-node}_fuel-core'
    environment:
      NETWORK_NAME: '${PROJECT} local'
      MIN_GAS_PRICE: ${MIN_GAS_PRICE}
      # This is the private key of the consensus.PoA.signing_key in the chainConfig.json
      # this key is responsible for validating the transactions
      CONSENSUS_KEY: ${WALLET_SECRET}
    build: ./fuel-core
    ports:
      - '${FUEL_CORE_PORT:-4000}:4000'
    volumes:
      - fuel-core-db:/mnt/db
    healthcheck:
      test: curl --fail http://localhost:4000/health || exit 1
      interval: 1s
      timeout: 5s
      retries: 20

  faucet:
    platform: linux/amd64
    container_name: '${PROJECT:-fuel-node}_faucet'
    environment:
      # Other configurations can be found at;
      # https://github.com/FuelLabs/faucet#configuration
      MIN_GAS_PRICE: ${MIN_GAS_PRICE}
      WALLET_SECRET_KEY: ${WALLET_SECRET}
      DISPENSE_AMOUNT: ${DISPENSE_AMOUNT}
      FUEL_NODE_URL: http://${PROJECT:-fuel-node}_fuel-core:4000/graphql
    image: ghcr.io/fuellabs/faucet:v0.6.2
    ports:
      - '${FUEL_FAUCET_PORT:-4040}:3000'
    links:
      - fuel-core
    depends_on:
      fuel-core:
        condition: service_healthy

volumes:
  fuel-core-db:
    name: '${PROJECT:-fuel-node}_fuel-core-db'
