/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.58.0
  Forc version: 0.44.0
  Fuel-Core version: 0.20.4
*/

export type { CustomAssetAbi } from './CustomAssetAbi';

export { CustomAssetAbi__factory } from './factories/CustomAssetAbi__factory';
