export enum Overlays {
  sidebar = 'sidebar',
  'accounts.list' = 'accounts.list',
  'accounts.add' = 'accounts.add',
  'accounts.import' = 'accounts.import',
  'accounts.export' = 'accounts.export',
  'accounts.edit' = 'accounts.edit',
  'accounts.logout' = 'accounts.logout',
  'networks.list' = 'networks.list',
  'networks.add' = 'networks.add',
  'networks.update' = 'networks.update',
  'transactions.approve' = 'transactions.approve',
  'settings.viewSeedPhrase' = 'settings.viewSeedPhrase',
  reset = 'reset',
}
