export const MOCK_CHAIN_INFO = {
  chain: {
    name: 'local_testnet',
    latestBlock: {
      id: '0x4a59174fe5a17015e3a1444e290409b6009db261455df4787f7e4dfe1ead33eb',
      height: '15',
      header: {
        time: '4611686020142482819',
      },
      transactions: [
        {
          id: '0x7c23856da804f76e038197ebb491b4db7db38c8857c69b74f97a04149fce892e',
        },
        {
          id: '0x046ef1b81bd0d4b57e96127feef1d48a34b2fb30c22e2ef5cef20b9460777d04',
        },
      ],
    },
    daHeight: '0',
    consensusParameters: {
      version: 'V1',
      txParams: {
        version: 'V1',
        maxInputs: '255',
        maxOutputs: '255',
        maxWitnesses: '255',
        maxGasPerTx: '30000000',
        maxSize: '112640',
        maxBytecodeSubsections: '256',
      },
      predicateParams: {
        version: 'V1',
        maxPredicateLength: '102400',
        maxPredicateDataLength: '102400',
        maxGasPerPredicate: '30000000',
        maxMessageDataLength: '102400',
      },
      scriptParams: {
        version: 'V1',
        maxScriptLength: '102400',
        maxScriptDataLength: '102400',
      },
      contractParams: {
        version: 'V1',
        contractMaxSize: '102400',
        maxStorageSlots: '1760',
      },
      feeParams: {
        version: 'V1',
        gasPriceFactor: '92',
        gasPerByte: '63',
      },
      gasCosts: {
        version: 'V1',
        add: '2',
        addi: '2',
        aloc: '1',
        and: '2',
        andi: '2',
        bal: '366',
        bhei: '2',
        bhsh: '2',
        burn: '33949',
        cb: '2',
        cfei: '2',
        cfsi: '2',
        div: '2',
        divi: '2',
        ecr1: '46165',
        eck1: '3347',
        ed19: '4210',
        eq: '2',
        exp: '2',
        expi: '2',
        flag: '1',
        gm: '2',
        gt: '2',
        gtf: '16',
        ji: '2',
        jmp: '2',
        jne: '2',
        jnei: '2',
        jnzi: '2',
        jmpf: '2',
        jmpb: '2',
        jnzf: '2',
        jnzb: '2',
        jnef: '2',
        jneb: '2',
        lb: '2',
        log: '754',
        lt: '2',
        lw: '2',
        mint: '35718',
        mlog: '2',
        modOp: '2',
        modi: '2',
        moveOp: '2',
        movi: '2',
        mroo: '5',
        mul: '2',
        muli: '2',
        mldv: '4',
        noop: '1',
        not: '2',
        or: '2',
        ori: '2',
        poph: '3',
        popl: '3',
        pshh: '4',
        pshl: '4',
        ret: '733',
        rvrt: '722',
        sb: '2',
        sll: '2',
        slli: '2',
        srl: '2',
        srli: '2',
        srw: '253',
        sub: '2',
        subi: '2',
        sw: '2',
        sww: '29053',
        time: '79',
        tr: '46242',
        tro: '33251',
        wdcm: '3',
        wqcm: '3',
        wdop: '3',
        wqop: '3',
        wdml: '3',
        wqml: '4',
        wddv: '5',
        wqdv: '7',
        wdmd: '11',
        wqmd: '18',
        wdam: '9',
        wqam: '12',
        wdmm: '11',
        wqmm: '11',
        xor: '2',
        xori: '2',
        call: {
          __typename: 'LightOperation',
          base: '21687',
          unitsPerGas: '4',
        },
        ccp: {
          __typename: 'LightOperation',
          base: '59',
          unitsPerGas: '20',
        },
        croo: {
          __typename: 'LightOperation',
          base: '1',
          unitsPerGas: '1',
        },
        csiz: {
          __typename: 'LightOperation',
          base: '59',
          unitsPerGas: '195',
        },
        k256: {
          __typename: 'LightOperation',
          base: '282',
          unitsPerGas: '3',
        },
        ldc: {
          __typename: 'LightOperation',
          base: '45',
          unitsPerGas: '65',
        },
        logd: {
          __typename: 'LightOperation',
          base: '1134',
          unitsPerGas: '2',
        },
        mcl: {
          __typename: 'LightOperation',
          base: '3',
          unitsPerGas: '523',
        },
        mcli: {
          __typename: 'LightOperation',
          base: '3',
          unitsPerGas: '526',
        },
        mcp: {
          __typename: 'LightOperation',
          base: '3',
          unitsPerGas: '448',
        },
        mcpi: {
          __typename: 'LightOperation',
          base: '7',
          unitsPerGas: '585',
        },
        meq: {
          __typename: 'LightOperation',
          base: '11',
          unitsPerGas: '1097',
        },
        retd: {
          __typename: 'LightOperation',
          base: '1086',
          unitsPerGas: '2',
        },
        s256: {
          __typename: 'LightOperation',
          base: '45',
          unitsPerGas: '3',
        },
        scwq: {
          __typename: 'HeavyOperation',
          base: '30375',
          gasPerUnit: '28628',
        },
        smo: {
          __typename: 'LightOperation',
          base: '64196',
          unitsPerGas: '1',
        },
        srwq: {
          __typename: 'HeavyOperation',
          base: '262',
          gasPerUnit: '249',
        },
        swwq: {
          __typename: 'HeavyOperation',
          base: '28484',
          gasPerUnit: '26613',
        },
        contractRoot: {
          __typename: 'LightOperation',
          base: '45',
          unitsPerGas: '1',
        },
        stateRoot: {
          __typename: 'HeavyOperation',
          base: '350',
          gasPerUnit: '176',
        },
        vmInitialization: {
          __typename: 'LightOperation',
          base: '1645',
          unitsPerGas: '14',
        },
        newStoragePerByte: '63',
      },
      baseAssetId:
        '0x0000000000000000000000000000000000000000000000000000000000000000',
      chainId: '0',
    },
  },
};
