version: "3"

services:
  fuel-core:
    container_name: "${PROJECT:-fuelhat}_fuel-core"
    environment:
      MIN_GAS_PRICE: ${GAS_PRICE}
    build: ../fuel-core
    ports:
      - "${FUEL_CORE_PORT:-4000}:4000"
    volumes:
      - fuel-core-db:/mnt/db
    healthcheck:
      test: curl --fail http://localhost:4000/health || exit 1
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  fuel-core-db:
    name: "${PROJECT:-fuelhat}_fuel-core-db"
