name: 'E2E Contract Tests'

inputs:
  ghToken:
    description: Github TOKEN
    required: true
  providerUrl:
    description: Provider URL (e.g. https://testnet.fuel.network/v1/graphql)
    required: true
  masterMnemonic:
    description: Mnemonic of the master wallet that will fund the tests
    required: true
  genesisSecret:
    description: Secret of genesis to fund the master wallet
    required: false
  skipDeploy:
    description: Skip deploying contracts
    required: false

runs:
  using: 'composite'
  steps:
    - uses: FuelLabs/github-actions/setups/node@master
      with:
        node-version: 18.18.0
        pnpm-version: 8.15.7
    - uses: FuelLabs/github-actions/setups/docker@master
      with:
        username: ${{ github.repository_owner }}
        password: ${{ inputs.ghToken }}

    - name: Run PNPM install
      id: pnpm-cache
      shell: bash
      run:
        pnpm recursive install --frozen-lockfile

    - name: Start Test Node
      shell: bash
      run: pnpm node:up

    - name: Generate .env app
      shell: bash
      run: cp packages/app/.env.example packages/app/.env

    - name: Generate .env e2e-contracts
      shell: bash
      run: cp packages/e2e-contract-tests/.env.example packages/e2e-contract-tests/.env

    - name: Build Application
      shell: bash
      run: pnpm build:all
      env:
        ## increase node.js m memory limit for building
        ## with sourcemaps
        NODE_OPTIONS: "--max-old-space-size=4096"
        NODE_ENV: test

    - name: Build & Deploy Contracts
      shell: bash
      if: !inputs.skipDeploy
      run: pnpm deploy:contracts
      working-directory: ./packages/e2e-contract-tests

    # E2E tests running with Playwright
    - name: Install Playwright Browsers
      shell: bash
      run: npx playwright install --with-deps chromium

    - name: Run E2E Contract Tests
      shell: bash
      run: xvfb-run --auto-servernum -- pnpm test:e2e:contracts
      env:
        NODE_ENV: test
        VITE_FUEL_PROVIDER_URL: ${{ inputs.providerUrl }}
        VITE_MASTER_WALLET_MNEMONIC: ${{ inputs.masterMnemonic }}
        VITE_WALLET_SECRET: ${{ inputs.genesisSecret }}

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: |
          packages/app/playwright-report/
          packages/app/playwright-html/
        retention-days: 30

    - name: Stop Test Node
      shell: bash
      run: pnpm node:clean
