name: Verify PR Requirements

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  verify-checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR checklist completion
        uses: actions/github-script@v6
        with:
          script: |
            const core = require('@actions/core');
            const pr = context.payload.pull_request;
            const prBody = pr.body || "";
            // RegEx to find any unchecked box "- [ ]"
            const unchecked = prBody.match(/- \[[ ]\]/);
            if (unchecked) {
              const errorMessage = "❌ Please complete all checklist items in the PR template before submitting your changes.";
              await github.rest.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                event: "REQUEST_CHANGES",
                body: errorMessage
              });
              core.setFailed("Not all checklist items are marked as completed.");
            } else {
              console.log("All checklist items are completed.");
            }

  verify-issue-reference:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR issue references
        uses: actions/github-script@v6
        with:
          script: |
            const core = require('@actions/core');
            const pr = context.payload.pull_request;
            const prBody = pr.body || "";
            // Check for a GitHub issue reference (e.g., Closes #123)
            const githubIssueRegex = /#\d+/;
            // Check for a Linear issue reference (pattern FE- followed by one or more digits)
            const linearIssueRegex = /FE-\d+/;
            const githubIssueMatch = prBody.match(githubIssueRegex);
            const linearIssueMatch = prBody.match(linearIssueRegex);
            let missingRefs = [];
            if (!githubIssueMatch) {
              missingRefs.push("GitHub Issue (e.g., Closes #123)");
            }
            if (!linearIssueMatch) {
              missingRefs.push("Linear Issue (e.g., FE-123)");
            }
            if (missingRefs.length > 0) {
              const errorMessage = "❌ Missing required references: " + missingRefs.join(" and ") + ". Please include both a GitHub issue and a Linear issue reference in your PR description.";
              await github.rest.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                event: "REQUEST_CHANGES",
                body: errorMessage
              });
              core.setFailed("Missing required issue references in the PR description.");
            } else {
              console.log("Both GitHub and Linear issue references are present in the PR.");
            }
