name: "PR sentry release"

on:
  pull_request:
    branches: [main, master]
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  relase-sentry:
    name: Relase Sentry to PR preview
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v3
      - uses: FuelLabs/github-actions/setups/node@master
      - uses: FuelLabs/github-actions/setups/docker@master
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Application
        run: pnpm build:crx
        env:
          ## increase node.js m memory limit for building
          ## with sourcemaps
          NODE_OPTIONS: "--max-old-space-size=4096"
          VITE_APP_VERSION: 0.0.10
      
      - name: Upload aritifacts to Sentry
        run: |
          cd ./packages/app
          ls ./dist-crx/assets
          pnpm sentry-cli sourcemaps inject --release 0.0.10 ./dist-crx
          pnpm sentry-cli sourcemaps upload --release 0.0.10 ./dist-crx
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

