name: Tests E2E - Assets Testnet

on:
  pull_request:
    branches: [main, master, sdk-v2]
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests-e2e-assets:
    name: Test
    runs-on: buildjet-8vcpu-ubuntu-2204
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Extract pnpm version from .tool-versions
        id: get_pnpm
        run: |
          PNPM_VERSION=$(grep '^pnpm' .tool-versions | awk '{print $2}')
          echo "PNPM_VERSION=${PNPM_VERSION}" >> $GITHUB_ENV

      - uses: FuelLabs/github-actions/setups/node@master
        with:
          node-version: 20.14.0
          pnpm-version: ${{ env.PNPM_VERSION }}

      - uses: ./.github/actions/setup-playwright

      - name: Run E2E Tests - Assets Testnet
        run: xvfb-run --auto-servernum -- pnpm test:e2e:assets
        timeout-minutes: 15
        env:
          NODE_ENV: test
          READONLY_TESTNET_ASSETS_VIEW: ${{ secrets.READONLY_TESTNET_ASSETS_VIEW }}

      - name: Upload Test Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-report
          path: packages/e2e-assets/playwright-html
