name: Release to @pr-<number> tag on npm

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  BUILD_VERSION: ""

jobs:
  release-changesets:
    name: Changesets Release
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: FuelLabs/github-actions/setups/node@master
      - uses: FuelLabs/github-actions/setups/npm@master
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Build Libs
        run: pnpm build:libs
        env:
          ## increase node.js m memory limit for building
          ## with sourcemaps
          NODE_OPTIONS: "--max-old-space-size=4096"
      
      - name: Release to @pr-${{ github.event.pull_request.number }} tag on npm
        id: release
        run: |
          pnpm changeset version --snapshot pr-${{ env.PR_NUMBER }}
          changetsets=$(pnpm changeset publish --tag pr-${{ env.PR_NUMBER }})
          published_version=$(echo "$changetsets" | grep -oP '@\K([0-9]+\.){2}[0-9]+-pr-${{ env.PR_NUMBER }}-\d+' | head -1)
          echo "published_version=$published_version" >> $GITHUB_OUTPUT
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
