name: Release to @preview tag on npm

on:
  # This should be removed before merging to master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  release-changesets:
    name: Changesets Release
    runs-on: buildjet-4vcpu-ubuntu-2204
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: FuelLabs/github-actions/setups/node@master
      - uses: FuelLabs/github-actions/setups/npm@master
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Build Libs
        run: pnpm build:libs
        env:
          ## increase node.js m memory limit for building
          ## with sourcemaps
          NODE_OPTIONS: "--max-old-space-size=4096"
      
      - name: Release to @preview tag on npm
        id: release
        run: |
          pnpm changeset version --snapshot preview
          changetsets=$(pnpm changeset publish --tag preview)
          published_version=$(echo "$changetsets" | grep -oP '@\K([0-9]+\.){2}[0-9]+-preview-\d+' | head -1)
          echo "published_version=$published_version" >> $GITHUB_OUTPUT
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: Comment release package name to PR
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            This PR is published in NPM with version **${{ steps.release.outputs.published_version }}**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
