name: Devnet tests

on:
  workflow_dispatch:
    inputs:
      masterMnemonic:
        description: Mnemonic of the wallet that will fund the tests
        required: false
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests-e2e-contracts:
    name: E2E Contract Tests - Devnet
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v3
      - uses: FuelLabs/github-actions/setups/node@master
        with:
          node-version: 20.11.0
          pnpm-version: 9.5.0
      - uses: FuelLabs/github-actions/setups/docker@master
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run PNPM install
        id: pnpm-cache
        run:
          pnpm recursive install --frozen-lockfile

      - name: Generate .env app
        run: cp packages/app/.env.example packages/app/.env

      - name: Generate .env e2e-contracts
        run: cp packages/e2e-contract-tests/.env.example packages/e2e-contract-tests/.env

      - name: Run E2E Contract Tests - Devnet
        uses: ./.github/actions/e2e-tests-contracts
        with:
          providerUrl: "https://devnet.fuel.network/v1/graphql"
          masterMnemonic: ${{ inputs.masterMnemonic || secrets.VITE_MASTER_WALLET_MNEMONIC }}
