# @TODO: REMOVE MYSELF, THIS IS ONLY FOR TESTING
name: "Release test"

on:
  pull_request:
    branches: [main, master, sdk-v2]
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_VERSION: ""

jobs:
  release-changesets:
    name: TESTTTTT Release master or rc
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v3
        with:
          # need this to get full git-history/clone in order to build changelogs and check changesets
          fetch-depth: 0
          # workaround to ensure force pushes to changeset branch use REPO_TOKEN owner's account
          # see https://github.com/changesets/action/issues/70
          persist-credentials: false
      - uses: FuelLabs/github-actions/setups/node@master
        with:
          node-version: 18.18.0
          pnpm-version: 8.15.7

      - name: Bump and Collect Version
        run: |
          pnpm changeset version
          echo "BUILD_VERSION=$(pnpm -s packages:version)" >> $GITHUB_ENV
          git reset --hard
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
