name: Update SDK version failed

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-pr-failure:
    runs-on: ubuntu-latest
    # Waiting intermitent errors being solved in our repo
    if: false
    # if: github.actor == 'github-actions[bot]' # Check if the PR is opened by the bot
    steps:
      - name: Check PR Build Status
        id: check_status
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prNumber = context.payload.pull_request.number;
            const result = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha
            });
            const failedChecks = result.data.check_runs.filter(check => check.conclusion == 'failure');
            return failedChecks.length > 0;

      - name: Extract Latest Version from PR
        id: extract_version
        if: steps.check_status.outputs.result == 'true'
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prBody = context.payload.pull_request.body;
            const versionMatch = prBody.match(/update sdk to (\S+)/i);
            const latestVersion = versionMatch ? versionMatch[1] : 'unknown';
            core.setOutput('latest_version', latestVersion);

      - name: Create GitHub Issue on PR Failure
        if: steps.check_status.outputs.result == 'true'
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const latestVersion = '${{ steps.extract_version.outputs.latest_version }}';
            const issueTitle = `PR Build Failed: #${context.payload.pull_request.number} - SDK v${latestVersion}`;
            const issueBody = `
              There was a failure in PR #${context.payload.pull_request.number}: ${context.payload.pull_request.html_url}
              The SDK update to version ${latestVersion} failed. Please investigate the cause of the failure.
            `;
            const repository = 'FuelLabs/fuels-ts'; // Replace with your target repository
            github.rest.issues.create({
              owner: repository.split('/')[0],
              repo: repository.split('/')[1],
              title: issueTitle,
              body: issueBody
            });
